### PR TITLE
Fixed execReaderF and execNonQueryF for Oracle

### PR DESCRIPTION
**Pull request by sbacquet**
Hi

FsSql does not work with Oracle (using execReaderF and execNonQueryF).
Thus, the parameter placeholder format is hard-coded to `@x`, whereas on Oracle it is `:x` in the SQL statement, and simply `x` for the mapped parameter name.
I've fixed that.

Please see https://docs.microsoft.com/fr-fr/dotnet/framework/data/adonet/configuring-parameters-and-parameter-data-types#working-with-parameter-placeholders.

### CODE REVIEW

**Review by czifro — COMMENTED** [review]
At a glance, this looks good.

**Comment by sbacquet** [comment]
Hello Irium
Do you plan to release a new version containing this fix ?
I'm using Oracle so I need it.
Thanks in advance !

**Comment by irium** [comment]
Published 3.1.0 version to NuGet with this change.

**Comment by sbacquet** [comment]
Excellent! Thanks a lot

**Pull request merged**
